# Generated by Django 3.2.22 on 2023-11-25 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_insert_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('main_insert_zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('main_insert_town_or_city', models.CharField(blank=True, max_length=40, null=True)),
                ('main_insert_street_address1', models.CharField(blank=True, max_length=80, null=True)),
                ('main_insert_street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('main_insert_county', models.CharField(blank=True, max_length=80, null=True)),
                ('main_insert_gender', models.CharField(blank=True, max_length=80, null=True)),
                ('main_insert_date_of_birth', models.DateTimeField()),
                ('scroll_user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
