# Generated by Django 3.2.22 on 2023-11-23 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_image'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLineObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('lineObject_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
        migrations.AlterField(
            model_name='customer_order',
            name='distribution_number',
            field=models.CharField(max_length=32),
        ),
        migrations.DeleteModel(
            name='OrderLineItem',
        ),
        migrations.AddField(
            model_name='orderlineobject',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineobjects', to='checkout.customer_order'),
        ),
    ]
