# Generated by Django 3.2.22 on 2023-11-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20231123_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='original_acquisition',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customer_order',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
